### ISSUE TITLE
middleware

### ISSUE THREAD

**Issue by aliuygur** [fromkeith/gorest#1]
how can i add middleware to routes ?

**Comment by fromkeith** [comment]
There is some, but no real middleware support.

You can register your own Marshallers using [RegisterMarshaller](https://github.com/fromkeith/gorest/blob/master/marshaller.go) to parse and format data (JSON, XML, From Encoding, etc...). So if you want to output "text/html" you could define your own marshaller that turns a method's output into HTML. You can see more about this in [Marshallers](http://godoc.org/github.com/fromkeith/gorest) section of the godoc.


Otherwise you can sit between gorest and the http.Handler:
```go
type simpleHandler struct {
    handler http.Handler
}
func NewSimpleHandler() http.Handler {
    return &simpleHandler{gorest.Handle()}
}
func (handler * simpleHandler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
    handler.handler.ServeHTTP(w, req)
}

```
and then register that handler:
```go
http.Handle("/r/", NewSimpleHandler())
```

and that's about it right now.

Is there something specific you want to solve?
